name: deploy
on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: deploy to gh-pages
    runs-on: ubuntu-22.04

    steps:
    - name: checkout source repo
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        path: source

    - name: copy meta files for cache
      run: |
        cp source/package.json .
        cp source/package-lock.json .

    - name: install node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # 3.4.1
      with:
        node-version: 18.7.0
        cache: npm

    - name: install dependencies
      working-directory: source
      run: npm i

    - name: build
      run: npm run build

    - name: checkout gh-pages branch
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        path: gh-pages
        ref: gh-pages

    # sorry I am lazy and don't want to learn bash scripting - Autumn
    - name: install fish
      run: |
        sudo add-apt-repository -yn ppa:fish-shell/release-3
        sudo apt-get update
        sudo apt-get install fish

    - name: publish
      shell: fish {0}
      run: |
        # clean
        rm -rf gh-pages/*
        mv gh-pages/.git gh-pages/git
        rm -rf gh-pages/.*
        mv gh-pages/git gh-pages/.git

        # copy output into gh-pages branch
        cp -R source/build/* gh-pages
        cp -R source/build/.* gh-pages

        cd source

        set COMMIT_MESSAGE "automated deploy from commit "(git rev-parse HEAD)

        cd ../gh-pages

        git config --global user.name ${{ github.event.pusher.name }}
        git config --global user.email ${{ github.event.pusher.email }}
        # the username used doesn't actually have to be anyone specific
        echo https://user:${{ secrets.GITHUB_TOKEN }}@github.com > .git/credentials
        git config --global credential.helper "store --file=.git/credentials"
        git config --unset-all http.https://github.com/.extraheader # https://stackoverflow.com/a/69979203

        git add -A
        git commit -m "$COMMIT_MESSAGE"
        git push
